name: Java CI

on: 
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: ./gradlew build
